# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Droidcon Paris 2015"
email: "contact@paug.fr"
description: "Droidcon Paris, the biggest Android event in France"
baseurl: "/zeppelin"
url: "https://cmoatoto2.github.io"
permalink: "/blog/:title"

# Organizer Info
organizerName: "Paris Android User Group & BeMyApp"
organizerAlternateName: "Paris Android User Group & BeMyApp"
organizerDescription: ""
organizerEmail: "contact@paug.fr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://paug.fr/"

# Head
metaKeywords: "event, gdg, droidcon, google, programming, android, wear, iot, glass, tv, developers, paris"
twitterAccount: "@droidconfr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/droidconfr-cfp"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://bit.ly/droidconfr-cfp", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/droidconfr-cfp", text: "Become a speaker"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Droidcon <typeout> 2015"
eventDate: "November, 2015"
typeoutTextValues: '"", "France", "Paris", "Android"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://bit.ly/droidconfr-cfp", text: "Become a speaker"}

# About Block
aboutTitle: "About Droidcon Paris"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Barcamp", image: "barcamp.jpg", text: "Come with your content and share directly with the audience." }
 - {title: "Party!", image: "party.jpg", text: "Let's talk & drink." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Android content"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Le Beffroi"
eventLocationLink: "http://beffroidemontrouge.com/"
eventStreetAddress: "2 Place Emile Cresp"
eventAddressLocality: "Montrouge"
eventAddressLocalityRegion: "Ile de France"
eventPostalCode: "92120"
eventAddressCountry: "France"
eventStartTime: "2015-11-09T09:00"
eventDoorTime: "09:00"
eventEndTime: "2015-11-10T20:00"
eventPlaceCoordinates: "48.81915, 2.319569"
mapCenterCoordinates: "48.81915, 2.319569"
mapMobileCenterCoordinates: "48.81915, 2.319569"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Le Beffroi"
venueFeatures: ["More than 10 000m<sup>2</sup>", "A 700+ attendees keynote room", "At the gateway of Paris"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "droidconfr"
twitterFeed: "http://cmoatoto.fr/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "€"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "€"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "€"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/103781206198600111125", icon: "google-plus"}
 - {link: "https://twitter.com/parisandroidug", icon: "twitter"}
 - {link: "https://www.facebook.com/ParisAndroidUG", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.paug.fr/", text: "PAUG.fr"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@paug.fr", text: "contact@paug.fr"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "48.81915, 2.319569"
logisticsMapMobileCenterCoordinates: "48.81915, 2.319569"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Paris"
directionDetailsCards:
 - {title: "From the Airports", information: 'Airports are close to Paris. It is easily reachable by car, public transport, Uber or taxi. You can find your way with <a href="http://www.ratp.fr/en/upload/docs/application/pdf/2014-07/depliant_aeroports_2014.pdf">this document</a>. You can also find the best way from <a href="http://www.ratp.fr/itineraires/fr/ratp/resultat-detaille/start/A%C3%A9roport+d%27Orly+Sud%2C+Paray-Vieille-Poste/end/2+Place+Emile+Cresp%2C+92120+Montrouge">Orly</a> or from <a href="http://www.ratp.fr/itineraires/fr/ratp/resultat-detaille/start/Aeroport+Charles+De+Gaulle+1+%28RER%29%2C+Tremblay-en-France/end/2+Place+Emile+Cresp%2C+92120+Montrouge">Roissy Charles De Gaulle</a>'}
 - {title: "Public Transit", information: 'Google Transit is available in Paris but without buses. So you can find most your way in Google Maps. Moreover, you can download the official <a href="https://play.google.com/store/apps/details?id=com.fabernovel.ratp&hl=fr">Paris transportation application</a>.'}
 - {title: "Hotels", information: 'Paris has lots of great hotels, hostels and AirBnB. If you have any trouble to find one, you can contact us.'}
